-- HV OPS — 001_init.sql
-- Enums + tables. Additive and re-runnable: nothing here drops or truncates anything.
-- Run on the NEW HV Ops Supabase project only (never on oawvsmcvqkyyhapetlqi).

-- gen_random_uuid() is built into Postgres 13+, no extension needed.

-- ---------------------------------------------------------------- enums
do $$ begin create type user_role as enum ('admin','manager','data_entry','marketing'); exception when duplicate_object then null; end $$;
do $$ begin create type listing_status as enum ('draft','ready_to_publish','published_claimed','verified_live','on_hold','rejected','archived'); exception when duplicate_object then null; end $$;
do $$ begin create type listing_source as enum ('sales_agent','owner','developer','whatsapp','walk_in','other'); exception when duplicate_object then null; end $$;
do $$ begin create type deal_type as enum ('sale','rent'); exception when duplicate_object then null; end $$;
do $$ begin create type channel_name as enum ('website','property_finder','aqarmap','olx','other'); exception when duplicate_object then null; end $$;
do $$ begin create type channel_status as enum ('not_started','in_progress','published','rejected'); exception when duplicate_object then null; end $$;
do $$ begin create type task_status as enum ('todo','doing','review','done','cancelled'); exception when duplicate_object then null; end $$;
do $$ begin create type task_priority as enum ('low','normal','high','urgent'); exception when duplicate_object then null; end $$;
do $$ begin create type agency_name as enum ('london_marketing_studios','izmi'); exception when duplicate_object then null; end $$;
do $$ begin create type deliverable_status as enum ('planned','submitted','approved','revision_requested','late','missed'); exception when duplicate_object then null; end $$;
do $$ begin create type alert_level as enum ('info','warning','critical'); exception when duplicate_object then null; end $$;

-- ---------------------------------------------------------------- profiles
create table if not exists profiles (
  id uuid primary key references auth.users(id),
  full_name text,
  email text,
  role user_role not null default 'data_entry',
  phone text,                                  -- E.164, for WhatsApp
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

-- ---------------------------------------------------------------- settings
create table if not exists settings (
  key text primary key,
  value jsonb not null,
  updated_by uuid references profiles(id),
  updated_at timestamptz not null default now()
);

-- ---------------------------------------------------------------- listings
create sequence if not exists listing_ref_seq start 2001;

create table if not exists listings (
  id uuid primary key default gen_random_uuid(),
  reference_code text unique not null,           -- HD-A-1012-S, generated by trigger
  title text,
  location text not null,
  property_type text not null,
  deal_type deal_type not null,
  -- The fields below are required for 100% completeness but nullable so a draft can be saved.
  area_sqm numeric,
  building_levels int,
  floor int,
  bedrooms int,
  bathrooms int,
  balconies int,
  furnished boolean,
  media_images_count int default 0,
  media_videos_count int default 0,
  media_drive_link text,
  is_exclusive boolean,
  view_type text,
  price numeric,
  currency text,                                 -- EUR | USD | EGP, never converted
  facilities text[] default '{}',
  selling_points text,
  buyer_persona_nationality text,
  buyer_persona_age_range text,
  buyer_persona_gender text,
  cover_photo_belongs boolean,
  date_received timestamptz not null default now(),   -- SLA clock start
  date_published_claimed timestamptz,
  date_published_verified timestamptz,                -- SLA clock stop (verifier only)
  source_type listing_source not null,
  source_name text not null,
  source_contact text,
  entered_by uuid not null references profiles(id),
  assigned_to uuid references profiles(id),
  status listing_status not null default 'draft',
  status_before_hold listing_status,
  hold_reason text,
  hold_started_at timestamptz,
  paused_seconds bigint not null default 0,           -- total on_hold time, excluded from SLA
  rejection_reason text,
  completeness_pct int not null default 0,
  missing_fields text[] default '{}',
  website_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists idx_listings_status on listings(status);
create index if not exists idx_listings_entered_by on listings(entered_by);
create index if not exists idx_listings_assigned_to on listings(assigned_to);
create index if not exists idx_listings_date_received on listings(date_received);

create table if not exists listing_channels (
  id uuid primary key default gen_random_uuid(),
  listing_id uuid not null references listings(id),
  channel channel_name not null,
  status channel_status not null default 'not_started',
  published_at timestamptz,
  url text,
  notes text,
  updated_by uuid references profiles(id),
  updated_at timestamptz not null default now(),
  unique (listing_id, channel)
);
create index if not exists idx_channels_listing on listing_channels(listing_id);

-- ---------------------------------------------------------------- verifier tables
create table if not exists wp_listing_index (
  id uuid primary key default gen_random_uuid(),
  reference_code text not null unique,
  url text,
  wp_published_at timestamptz,
  first_seen_at timestamptz not null default now(),
  method text,
  raw jsonb
);

-- one row per website page the verifier has looked at, so it never re-fetches unchanged pages
create table if not exists wp_crawl_log (
  url text primary key,
  wp_published_at timestamptz,
  wp_modified_at timestamptz,
  reference_code text,
  http_status int,
  last_fetched_at timestamptz not null default now()
);

create table if not exists verifier_runs (
  id uuid primary key default gen_random_uuid(),
  started_at timestamptz not null default now(),
  finished_at timestamptz,
  method text,                                   -- 'rest+html' | 'sitemap+html'
  pages_listed int default 0,
  pages_fetched int default 0,
  refs_found int default 0,
  listings_verified int default 0,
  alerts_created int default 0,
  pending_pages int default 0,
  error text
);

-- ---------------------------------------------------------------- tasks
create table if not exists recurring_templates (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  description text,
  task_type text,
  assigned_to uuid references profiles(id),
  priority task_priority not null default 'normal',
  frequency text not null check (frequency in ('daily','weekly','monthly')),
  weekday int check (weekday between 0 and 6),   -- 0 = Sunday
  day_of_month int check (day_of_month between 1 and 31),
  due_time time not null default '17:00',
  is_active boolean not null default true,
  created_by uuid references profiles(id),
  created_at timestamptz not null default now()
);

create table if not exists tasks (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  description text,
  task_type text,
  assigned_to uuid references profiles(id),
  created_by uuid references profiles(id),
  status task_status not null default 'todo',
  priority task_priority not null default 'normal',
  due_at timestamptz,
  started_at timestamptz,
  completed_at timestamptz,                      -- when the work was submitted (review) or finished
  approved_by uuid references profiles(id),
  approved_at timestamptz,
  rejection_reason text,
  listing_id uuid references listings(id),
  agency agency_name,
  recurring_template_id uuid references recurring_templates(id),
  recurring_for_date date,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
-- not partial on purpose: the worker upserts with ON CONFLICT on these columns (NULLs never conflict)
create unique index if not exists uq_tasks_recurring on tasks(recurring_template_id, recurring_for_date);
create index if not exists idx_tasks_assigned on tasks(assigned_to);
create index if not exists idx_tasks_status on tasks(status);

-- ---------------------------------------------------------------- agencies
create table if not exists agencies (
  id uuid primary key default gen_random_uuid(),
  name agency_name not null unique,
  display_name text not null,
  contact_person text,
  contact_email text,
  contact_phone text,
  contract_start date,
  contract_end date,
  monthly_fee numeric,
  currency text,
  scope_notes text,
  is_active boolean not null default true
);

create table if not exists agency_deliverables (
  id uuid primary key default gen_random_uuid(),
  agency_id uuid not null references agencies(id),
  period_month date not null,                    -- first of month
  item_type text not null,
  planned_qty int not null default 0,
  due_date date,
  delivered_qty int not null default 0,
  delivered_at timestamptz,
  status deliverable_status not null default 'planned',
  revisions_count int not null default 0,
  logged_by uuid references profiles(id),
  approved_by uuid references profiles(id),
  approved_at timestamptz,
  notes text,
  proof_url text,
  created_at timestamptz not null default now()
);
create index if not exists idx_deliv_agency_month on agency_deliverables(agency_id, period_month);

create table if not exists agency_metrics (
  id uuid primary key default gen_random_uuid(),
  agency_id uuid not null references agencies(id),
  period_month date not null,
  metric_key text not null,
  metric_value numeric,
  unit text,
  entered_by uuid references profiles(id),
  source text not null default 'manual' check (source in ('manual','supermetrics','ga4')),
  created_at timestamptz not null default now(),
  unique (agency_id, period_month, metric_key)
);

create table if not exists kpi_targets (
  id uuid primary key default gen_random_uuid(),
  subject_type text not null check (subject_type in ('user','agency','team')),
  subject_id uuid,
  period_month date not null,
  metric_key text not null,
  target_value numeric,
  created_by uuid references profiles(id),
  created_at timestamptz not null default now()
);
create unique index if not exists uq_kpi_targets on kpi_targets(subject_type, subject_id, period_month, metric_key);

-- ---------------------------------------------------------------- alerts / audit / snapshots
create table if not exists alerts (
  id uuid primary key default gen_random_uuid(),
  level alert_level not null default 'info',
  title text not null,
  body text,
  entity_type text,
  entity_id uuid,
  target_user uuid references profiles(id),
  target_role user_role,
  is_read boolean not null default false,
  whatsapp_sent boolean not null default false,
  dedupe_key text unique,                        -- stops the hourly worker repeating the same alert
  created_at timestamptz not null default now()
);
create index if not exists idx_alerts_target on alerts(target_user, is_read);

create table if not exists audit_log (
  id bigserial primary key,
  table_name text not null,
  record_id uuid,
  action text not null,                          -- insert | update | delete_soft
  field_name text,
  old_value text,
  new_value text,
  changed_by uuid,
  changed_at timestamptz not null default now(),
  ip text
);
create index if not exists idx_audit_record on audit_log(table_name, record_id);

create table if not exists report_snapshots (
  id uuid primary key default gen_random_uuid(),
  report_type text not null,                     -- daily | weekly | monthly | custom
  period_start date not null,
  period_end date not null,
  title text,
  payload jsonb not null,
  created_by uuid references profiles(id),
  created_at timestamptz not null default now()
);
