-- HV OPS — 011_projects.sql   (Daniel, 2026-09-19)
-- Projects (developer compounds / resorts) go through the same two-stage pipeline as units:
--   ENTRY (data + photos)  ->  ready  ->  UPLOAD to the website  ->  verified live by the verifier.
-- What the website shows (checked on all 54 live projects): a "Project ID" in the Technical Specifications block.
--   Company convention:  P-LOC-SERIAL-S      e.g. P-MG-929-S, P-VR-925-S, P-G-918-S
--     P = project, LOC = same location letters as units, SERIAL = the projects' OWN running number (separate from units;
--     highest on the site is 929, so the next is 930), S = sale.
--   IDs like PRJ-013330 are NOT company codes: the website fills in the WordPress post number when nobody typed a Project ID.
-- Column names deliberately match ops_listings so the same guard / stamps / audit trigger functions are reused.
-- Additive, safe to re-run.

create table if not exists ops_projects (
  id uuid primary key default gen_random_uuid(),
  reference_code text unique not null,               -- P-MG-930-S, generated by trigger; pasted into WordPress "Project ID"
  name text not null,
  developer text,
  location text not null,
  project_types text[] default '{}',                 -- Apartment / Villa / Resort / Compound ... (website "project_type")
  unit_sizes text,                                   -- "57 – 180 m² (Studios, 1BR, 2BR)"
  bedrooms text,                                     -- "Studio, 1–3 BR"
  starting_price numeric,
  currency text,                                     -- never converted
  down_payment text,                                 -- "10%"
  installments text,                                 -- "7 years, quarterly"
  delivery_date text,                                -- "December 2027" / "3 years from contract" / "Available"
  finishing text,
  facilities text[] default '{}',
  selling_points text,
  is_exclusive boolean,
  media_uploaded boolean,                            -- photos/brochure ready = approved by the manager (files stay on the intranet)
  media_has_logo boolean,
  media_edited boolean,
  media_approved_by uuid references public.app_users(id),
  media_approved_at timestamptz,
  source_name text,                                  -- developer's contact person
  source_contact text,
  date_received timestamptz not null default now(),  -- SLA clock start
  date_ready timestamptz,
  date_published_claimed timestamptz,
  published_claimed_by uuid references public.app_users(id),
  date_published_verified timestamptz,               -- verifier only
  entered_by uuid not null references public.app_users(id),
  assigned_to uuid references public.app_users(id),
  status ops_listing_status not null default 'draft',
  status_before_hold ops_listing_status,
  hold_reason text,
  hold_started_at timestamptz,
  paused_seconds bigint not null default 0,
  rejection_reason text,
  completeness_pct int not null default 0,
  missing_fields text[] default '{}',
  website_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists ops_idx_projects_status on ops_projects(status);
create index if not exists ops_idx_projects_entered_by on ops_projects(entered_by);
create index if not exists ops_idx_projects_assigned_to on ops_projects(assigned_to);

create table if not exists ops_wp_project_index (
  id uuid primary key default gen_random_uuid(),
  reference_code text not null unique,
  url text,
  wp_published_at timestamptz,
  first_seen_at timestamptz not null default now(),
  method text,
  raw jsonb
);

insert into ops_settings (key, value) values
('project_required_fields', '["name","developer","location","project_types","unit_sizes","starting_price","currency","down_payment","delivery_date","finishing","facilities","selling_points","media_uploaded"]'::jsonb),
('project_sla_hours', '{"warn":120,"breach":168,"incomplete_alert":48,"claim_grace":24}'::jsonb),
('project_types', '["Apartment","Studio","Villa","Townhouse","Penthouse","Chalet","Duplex","Compound","Resort"]'::jsonb),
('finishing_types', '["Fully Finished","Fully Finished & Furnished","Semi-Finished","Core & Shell","To be confirmed"]'::jsonb)
on conflict (key) do nothing;

-- ---------------------------------------------------------------- completeness: the required-field list is chosen per table
-- trigger argument = the ops_settings key to read (default: required_fields, i.e. units)
create or replace function ops_fn_calc_completeness() returns trigger
language plpgsql security definer set search_path = public as $$
declare
  req jsonb; row_j jsonb := to_jsonb(new); f text; v jsonb;
  total int := 0; filled int := 0; missing text[] := '{}';
  list_key text := coalesce(tg_argv[0], 'required_fields');
begin
  select value into req from ops_settings where key = list_key;
  if req is null or jsonb_typeof(req) <> 'array' then return new; end if;

  for f in select jsonb_array_elements_text(req) loop
    if not (row_j ? f) then continue; end if;
    total := total + 1;
    v := row_j -> f;
    if v is null or jsonb_typeof(v) = 'null'
       or (jsonb_typeof(v) = 'string' and btrim(v #>> '{}') = '')
       or (jsonb_typeof(v) = 'array'  and jsonb_array_length(v) = 0)
       or (f in ('media_images_count','media_videos_count','area_sqm','price','starting_price') and jsonb_typeof(v) = 'number' and (v #>> '{}')::numeric <= 0)
       or (f = 'media_uploaded' and v = 'false'::jsonb)
    then missing := array_append(missing, f);
    else filled := filled + 1;
    end if;
  end loop;

  new.completeness_pct := case when total = 0 then 100 else floor(100.0 * filled / total)::int end;
  new.missing_fields := missing;
  return new;
end $$;

-- ---------------------------------------------------------------- project code  P-LOC-SERIAL-S , serial = last project serial + 1
create or replace function ops_fn_generate_project_code() returns trigger
language plpgsql security definer set search_path = public as $$
declare loc_code text; n bigint; candidate text;
begin
  if new.reference_code is not null and btrim(new.reference_code) <> '' then
    new.reference_code := upper(regexp_replace(new.reference_code, '\s', '', 'g'));   -- importing an existing project keeps the site's ID
    return new;
  end if;
  select value ->> new.location into loc_code from ops_settings where key = 'location_codes';
  if loc_code is null then raise exception 'No location code for "%". Add it in Settings > Location codes.', new.location; end if;

  perform pg_advisory_xact_lock(hashtext('ops_project_serial'));
  -- only real company codes count (P-…-###-S); website auto-IDs such as PRJ-013330 are ignored
  select coalesce(max((regexp_match(upper(reference_code), '-(\d{1,6})-S$'))[1]::bigint), 0) + 1 into n
  from (select reference_code from ops_wp_project_index union all select reference_code from ops_projects) r
  where upper(reference_code) ~ '^P-.*-\d{1,6}-S$';

  loop
    candidate := 'P-' || upper(loc_code) || '-' || n || '-S';
    exit when not exists (select 1 from ops_projects where reference_code = candidate)
          and not exists (select 1 from ops_wp_project_index where upper(reference_code) = candidate);
    n := n + 1;
  end loop;
  new.reference_code := candidate;
  return new;
end $$;

drop trigger if exists trg_a_refcode on ops_projects;
create trigger trg_a_refcode before insert on ops_projects for each row execute function ops_fn_generate_project_code();
drop trigger if exists trg_b_completeness on ops_projects;
create trigger trg_b_completeness before insert or update on ops_projects for each row execute function ops_fn_calc_completeness('project_required_fields');
drop trigger if exists trg_c_guard on ops_projects;      -- same rules as units: code immutable, verifier-only verified_live, manager-only photo approval, holds…
create trigger trg_c_guard before insert or update on ops_projects for each row execute function ops_fn_listing_guard();
drop trigger if exists trg_d_stamps on ops_projects;
create trigger trg_d_stamps before insert or update on ops_projects for each row execute function ops_fn_listing_stamps();
drop trigger if exists trg_audit on ops_projects;
create trigger trg_audit after insert or update on ops_projects for each row execute function ops_fn_audit();

-- ---------------------------------------------------------------- RLS (same shape as units)
alter table ops_projects enable row level security;
alter table ops_wp_project_index enable row level security;
revoke delete, truncate on ops_projects, ops_wp_project_index from anon, authenticated;
revoke all on ops_projects, ops_wp_project_index from anon;

drop policy if exists projects_select on ops_projects;
create policy projects_select on ops_projects for select to authenticated using (public.ops_is_staff());
drop policy if exists projects_insert on ops_projects;
create policy projects_insert on ops_projects for insert to authenticated
  with check (public.ops_is_mgr() or (public.ops_is_staff() and entered_by = auth.uid()));
drop policy if exists projects_update on ops_projects;
create policy projects_update on ops_projects for update to authenticated
  using (public.ops_is_mgr() or (public.ops_is_staff() and (entered_by = auth.uid() or assigned_to = auth.uid())))
  with check (public.ops_is_mgr() or (public.ops_is_staff() and (entered_by = auth.uid() or assigned_to = auth.uid())));
drop policy if exists wpprojects_select on ops_wp_project_index;
create policy wpprojects_select on ops_wp_project_index for select to authenticated using (public.ops_is_staff());

-- ---------------------------------------------------------------- HR KPIs: a project is a bigger job than a unit
insert into public.kpi_metrics (code, name_en, name_ar, points_per_unit, value_points_per_million, has_value, sort, category) values
  ('ops_project_ready',   'Project entered complete (ready to publish)', 'مشروع مُدخل كامل وجاهز للنشر',        8, 0, false, 24, 'operations'),
  ('ops_project_live',    'Project uploaded & verified live',            'مشروع مرفوع ومؤكد على الموقع',        5, 0, false, 25, 'operations'),
  ('ops_project_on_time', 'Project published within SLA',                'مشروع منشور خلال المهلة',             3, 0, false, 26, 'operations')
on conflict (code) do nothing;

create or replace function public.ops_kpi_from_project() returns trigger
language plpgsql security definer set search_path = public as $$
declare breach numeric; hrs numeric; uploader uuid;
begin
  if new.date_ready is not null and old.date_ready is null then
    perform public.ops_kpi_credit(new.entered_by, 'ops_project_ready', new.date_ready::date, new.reference_code || ' · ' || new.name,
                                  'ops:pready:' || new.id, 'HV Ops: project entered complete');
  end if;
  if new.date_published_verified is not null and old.date_published_verified is null then
    uploader := coalesce(new.published_claimed_by, new.assigned_to, new.entered_by);
    perform public.ops_kpi_credit(uploader, 'ops_project_live', new.date_published_verified::date, new.reference_code || ' · ' || new.name,
                                  'ops:plive:' || new.id, 'HV Ops: project verified live ' || coalesce(new.website_url, ''));
    select coalesce((value ->> 'breach')::numeric, 168) into breach from ops_settings where key = 'project_sla_hours';
    hrs := greatest(0, extract(epoch from (new.date_published_verified - new.date_received)) - new.paused_seconds) / 3600.0;
    if hrs <= coalesce(breach, 168) then
      perform public.ops_kpi_credit(uploader, 'ops_project_on_time', new.date_published_verified::date, new.reference_code,
                                    'ops:pontime:' || new.id, 'HV Ops: project published in ' || round(hrs, 1) || 'h');
    end if;
  elsif new.status = 'rejected' and old.status is distinct from new.status then
    update kpi_entries set status = 'rejected', notes = coalesce(notes, '') || ' | project rejected'
     where external_id in ('ops:pready:' || new.id, 'ops:plive:' || new.id, 'ops:pontime:' || new.id);
  end if;
  return new;
end $$;

drop trigger if exists trg_z_kpi on ops_projects;
create trigger trg_z_kpi after update on ops_projects for each row execute function public.ops_kpi_from_project();

-- KPI tiles inside HV Ops
update ops_settings set updated_at = now(), value = value || '[
  {"key":"projects_entered","label":"Projects entered","unit":"count","team":"data_entry","part":"entry","better":"high"},
  {"key":"projects_uploaded","label":"Projects uploaded","unit":"count","team":"data_entry","part":"upload","better":"high"}
]'::jsonb
where key = 'user_kpi_defs' and not (value @> '[{"key":"projects_entered"}]'::jsonb);
